spring:
  application:
    name: bh-eureka-server
server:
  port: 8701
eureka:
  instance:
    hostname: eurekaSer
    preferIpAddress: true
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    instanceId: ${spring.cloud.client.hostname}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaSerHA:8702/eureka/
